server:
  port: 8080

spring:
  application:
    name: Tresoro

  datasource:
    url: jdbc:mysql://localhost:3306/tresoro
    username: root
    password: vampire
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

tresoro:
  jwt:
    secret-key: 0cb8480164ea5f886a49e5d95541cd4b604f52a335c3c44960de5fd48085e4e4
  admin:
    secret-key: 7e1749b675b73f5e3b4a38b4b3443961f8f57d131c911577b7c7e79b8f9ae848